#!/bin/bash

OS=$1
TARGETARCH=$2

SCRIPTDIR=$(realpath $(dirname $0))
PLATFORMS_JSON="$SCRIPTDIR/platforms.json"

COMPILEROS_JSONPATH=".$OS.name"
COMPILEROS=$(cat $PLATFORMS_JSON | jq -r $COMPILEROS_JSONPATH)

COMPILERARCH_JSONPATH=".$OS.architectures.$TARGETARCH"
COMPILERARCH=$(cat $PLATFORMS_JSON | jq -r $COMPILERARCH_JSONPATH)

CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_SYSTEM_NAME=$OS"
CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_SYSTEM_PROCESSOR=$COMPILERARCH"
CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_C_COMPILER=$COMPILERARCH-$COMPILEROS-gcc"
CMAKE_ARGS="$CMAKE_ARGS -DCMAKE_FIND_ROOT_PATH=/usr/$COMPILERARCH-$COMPILEROS"

if ! cmake . -B build $CMAKE_ARGS; then
    exit 1
fi

if ! cmake --build build -j 8; then
    exit 1
fi
