name: deploy
permissions:
    contents: read
    packages: write
on:
    push:
        branches:
          - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
            with:
                submodules: recursive
                token: ${{ secrets.PAT }}
          - uses: docker/setup-buildx-action@v2
            with:
                platforms: linux/amd64,linux/arm64
          - uses: docker/login-action@v2
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.PAT }}
          - name: get image name
            shell: bash
            run: echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
          - name: build & push
            uses: docker/build-push-action@v4
            with:
                push: true
                tags: ghcr.io/${{ env.REPO }}:${{ github.sha }},ghcr.io/${{ env.REPO }}:latest
                file: ./Dockerfile
                context: .
                github-token: ${{ secrets.PAT }}
                platforms: linux/amd64,linux/arm64
